# Generated by Django 4.2.3 on 2023-08-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='date_joined',
            new_name='creation_date',
        ),
    ]
